package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"time"

	"github.com/g-192/stickerdrop/graph/model"
)

// ClaimSticker is the resolver for the claimSticker field.
func (r *mutationResolver) ClaimSticker(ctx context.Context, dropID string, email string) (bool, error) {
	redisKey := fmt.Sprintf("drop:%s:email:%s", dropID, email)

	isNew, err := r.Redis.SetNX(ctx, redisKey, "claimed", 24*time.Hour).Result()
	if err != nil {
		return false, fmt.Errorf("Redis Error: %v", err)
	}
	if !isNew {
		return false, fmt.Errorf("You already participated in this drop!")
	}

	query := `
		UPDATE drops 
		SET claimed = claimed + 1 
		WHERE id = $1 AND claimed < total_available
	`

	tag, err := r.DB.Exec(ctx, query, dropID)
	if err != nil {
		// if Postgres crashes, return E-Mail from Redis
		r.Redis.Del(ctx, redisKey)
		return false, fmt.Errorf("DB Error: %v", err)
	}

	if tag.RowsAffected() == 0 {
		r.Redis.Del(ctx, redisKey) // return E-Mail again
		return false, fmt.Errorf("I'm sorry, the Stickers are already given out!")
	}

	return true, nil
}

// GetDrop is the resolver for the getDrop field.
func (r *queryResolver) GetDrop(ctx context.Context, id string) (*model.Drop, error) {
	var drop model.Drop

	err := r.DB.QueryRow(ctx, "SELECT id, title, total_available, claimed FROM drops WHERE id = $1", id).
		Scan(&drop.ID, &drop.Title, &drop.TotalAvailable, &drop.Claimed)

	if err != nil {
		return nil, fmt.Errorf("Drop not found or there is an error: %v", err)
	}

	return &drop, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
