// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Drop struct {
	ID             string `json:"id"`
	Title          string `json:"title"`
	TotalAvailable int32  `json:"totalAvailable"`
	Claimed        int32  `json:"claimed"`
}

type Mutation struct {
}

type Query struct {
}
